services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_bot
    command: python manage.py run_bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_admin
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  nginx:
    image: nginx:latest
    container_name: bot_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - admin

volumes:
  postgres_data:
  static_volume: