# Generated by Django 5.1.2 on 2024-11-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='никнейм')),
                ('chat_id', models.CharField(max_length=120, unique=True, verbose_name='chat_id чтобы запомнить при выходе')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='код доступа')),
                ('user', models.OneToOneField(blank=True, max_length='пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Код доступа',
                'verbose_name_plural': 'Коды доступа',
            },
        ),
    ]
