# Generated by Django 5.1.2 on 2024-11-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='work_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип работы'),
        ),
    ]
