# Generated by Django 5.1.2 on 2024-11-07 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramuser_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начала'),
            preserve_default=False,
        ),
    ]
