# Generated by Django 5.1.2 on 2024-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='timepad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество таймпадов'),
        ),
    ]
