# Generated by Django 5.1.2 on 2024-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_category_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='mood_second_month',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='настроение на втором месяце'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='mood_third_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='настроение в третий день'),
        ),
    ]
