# Generated by Django 5.1.2 on 2024-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_telegramuser_mood_second_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='форма взаимодействия'),
        ),
    ]
