# Generated by Django 5.1.2 on 2024-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_telegramuser_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Управление пользователями', 'verbose_name_plural': 'Управление пользователями'},
        ),
        migrations.AddField(
            model_name='faq',
            name='name',
            field=models.TextField(default=1, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='buddy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Бадди'),
        ),
        migrations.AlterField(
            model_name='code',
            name='start_date',
            field=models.DateField(verbose_name='Дата первого рабочего дня'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='post',
            field=models.URLField(verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма взаимодействия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='mood_second_month',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Настроение через 2 месяца'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='mood_third_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Настроение на 3 день'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='timepad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество таймпадов'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
