# Generated by Django 5.1.2 on 2024-12-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_faq_category_delete_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreonbordingLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquaintance', models.URLField(blank=True, null=True, verbose_name='форма для знакомства')),
                ('emails', models.CharField(blank=True, null=True, verbose_name='почтовые адреса для оформления документов')),
                ('address', models.URLField(blank=True, null=True, verbose_name='адрес офиса (ссылка на yandex map)')),
            ],
            options={
                'verbose_name': 'Преонбординг',
                'abstract': False,
            },
        ),
    ]
