# Generated by Django 5.1.2 on 2024-12-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_firstday_fourthday_monthhalf_secondday_secondmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstday',
            name='hr_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт hr'),
        ),
    ]
