# Generated by Django 5.1.2 on 2024-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_firstday_hr_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstday',
            name='link_admin',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='контакт админа Барахолка и свопы'),
        ),
    ]
