# Generated by Django 5.1.2 on 2024-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_firstday_link_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='post',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
