# Generated by Django 5.1.2 on 2024-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_firstday_system_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthhalf',
            name='survey_link',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLScEQfKbumuqSd_3DeR1WDtQJUt5fYvUQEnGFJWgqXLmm9MLyQ/viewform', verbose_name='Ссылка на анкету'),
        ),
        migrations.AlterField(
            model_name='secondmonth',
            name='hr_link',
            field=models.URLField(default='https://us02web.zoom.us/j/86826507585?pwd=qmo2josZPIVmEJzV8cnrd3FRKlIjl7.1', verbose_name='Ссылка на встречу'),
        ),
        migrations.AlterField(
            model_name='thirdmonth',
            name='meet_link',
            field=models.URLField(default='https://docs.google.com/forms/d/e/1FAIpQLSf1X3GgiJ2x8-x-XXVearUhGp5tTYkX-_bI7hQX7OBCOzh4Qg/viewform', verbose_name='Ссылка на встречу'),
        ),
    ]
