# Generated by Django 5.1.2 on 2024-12-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_monthhalf_survey_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.IntegerField(default=1, verbose_name='день'),
            preserve_default=False,
        ),
    ]
