# Generated by Django 5.1.2 on 2024-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_userconversationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='emodji',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='описывает твои идеальные выходные'),
        ),
    ]
